name: Backend Linting and Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy

      - name: Run Ruff for linting
        run: |
          echo "Running Ruff for linting..."
          ruff check ./backend

      - name: Run Black for formatting checks
        run: |
          echo "Running Black for formatting checks..."
          black --check ./backend

      - name: Run Mypy for type checks
        run: |
          echo "Running Mypy for type checks..."
          mypy ./backend
